@extends('layouts.app')
@section('title', 'Staff Attendance')
@section('content')
<div class="panel">
    <div class="flex flex-wrap items-start justify-between gap-4"><div><h2 class="panel-title">Staff Attendance</h2><p class="panel-subtitle">Tenant-scoped daily attendance. One record per employee and date.</p></div>@can('create', App\Models\StaffAttendance::class)<a class="button" href="{{ route('staff-attendance.create') }}">+ Record attendance</a>@endcan</div>
    <form method="GET" class="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><select class="input" name="faculty_id"><option value="">All employees</option>@foreach($employees as $employee)<option value="{{ $employee->id }}" @selected((int)($filters['faculty_id'] ?? 0) === $employee->id)>{{ $employee->full_name }} ({{ $employee->employee_code }})</option>@endforeach</select><input class="input" type="date" name="from" value="{{ $filters['from'] ?? '' }}"><input class="input" type="date" name="to" value="{{ $filters['to'] ?? '' }}"><select class="input" name="status"><option value="">All statuses</option>@foreach($statuses as $status)<option value="{{ $status }}" @selected(($filters['status'] ?? '') === $status)>{{ ucfirst($status) }}</option>@endforeach</select><div class="flex gap-2"><button class="button" type="submit">Filter</button><a class="button !bg-slate-200 !text-slate-700" href="{{ route('staff-attendance.index') }}">Clear</a></div></form>
    <div class="mt-8 overflow-x-auto"><table class="w-full text-left text-sm"><thead><tr class="border-b text-slate-500"><th class="py-3">Date</th><th>Employee</th><th>Status</th><th>Remarks</th><th class="text-right">Actions</th></tr></thead><tbody>@forelse($attendances as $attendance)<tr class="border-b"><td class="py-3">{{ $attendance->attendance_date?->format('d M Y') }}</td><td class="font-medium">{{ $attendance->employee?->full_name }}<div class="text-xs text-slate-500">{{ $attendance->employee?->employee_code }}</div></td><td><span class="rounded-full bg-slate-100 px-2 py-0.5 text-xs font-semibold">{{ ucfirst($attendance->status) }}</span></td><td>{{ $attendance->remarks ?: '—' }}</td><td class="text-right"><div class="flex justify-end gap-2">@can('update', $attendance)<a class="text-xs font-semibold text-indigo-600 hover:underline" href="{{ route('staff-attendance.edit', $attendance) }}">Correct</a>@endcan @can('delete', $attendance)<form method="POST" action="{{ route('staff-attendance.destroy', $attendance) }}">@csrf @method('DELETE')<button class="text-xs font-semibold text-rose-600 hover:underline" type="submit">Delete</button></form>@endcan</div></td></tr>@empty<tr><td colspan="5" class="py-6 text-slate-500">No attendance records found.</td></tr>@endforelse</tbody></table></div><div class="mt-4">{{ $attendances->links() }}</div>
</div>
@endsection
