@extends('layouts.app')
@section('title', 'Leave Management')
@section('content')
<div class="panel">
    <div class="flex flex-wrap items-start justify-between gap-4"><div><h2 class="panel-title">Leave Management</h2><p class="panel-subtitle">Submit, approve, reject, or cancel staff leave. Approved dates cannot overlap.</p></div><div class="flex gap-2">@can('create', App\Models\LeaveRequest::class)<a class="button" href="{{ route('leave-requests.create') }}">+ New request</a>@endcan @can('create', App\Models\LeaveType::class)<a class="button !bg-slate-200 !text-slate-700" href="{{ route('leave-types.index') }}">Leave types</a>@endcan</div></div>
    <form method="GET" class="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><select class="input" name="faculty_id"><option value="">All employees</option>@foreach($employees as $employee)<option value="{{ $employee->id }}" @selected((int)($filters['faculty_id'] ?? 0) === $employee->id)>{{ $employee->full_name }}</option>@endforeach</select><select class="input" name="status"><option value="">All statuses</option>@foreach($statuses as $status)<option value="{{ $status }}" @selected(($filters['status'] ?? '') === $status)>{{ ucfirst($status) }}</option>@endforeach</select><input class="input" type="date" name="from" value="{{ $filters['from'] ?? '' }}"><input class="input" type="date" name="to" value="{{ $filters['to'] ?? '' }}"><button class="button" type="submit">Filter</button></form>
    <div class="mt-8 overflow-x-auto"><table class="w-full text-left text-sm"><thead><tr class="border-b text-slate-500"><th class="py-3">Employee</th><th>Leave type</th><th>Dates</th><th>Days</th><th>Status</th><th class="text-right">Actions</th></tr></thead><tbody>@forelse($requests as $leaveRequest)<tr class="border-b"><td class="py-3 font-medium">{{ $leaveRequest->employee?->full_name }}</td><td>{{ $leaveRequest->leaveType?->name }}</td><td>{{ $leaveRequest->from_date?->format('d M Y') }} – {{ $leaveRequest->to_date?->format('d M Y') }}</td><td>{{ $leaveRequest->days }}</td><td><span class="rounded-full bg-slate-100 px-2 py-0.5 text-xs font-semibold">{{ ucfirst($leaveRequest->status) }}</span></td><td class="text-right"><div class="flex flex-wrap justify-end gap-2">@can('update', $leaveRequest)<a class="text-xs text-indigo-600" href="{{ route('leave-requests.edit', $leaveRequest) }}">Edit</a>@endcan @can('approve', $leaveRequest) @if($leaveRequest->isPending())<form method="POST" action="{{ route('leave-requests.approve', $leaveRequest) }}">@csrf<button class="text-xs text-emerald-600" type="submit">Approve</button></form><form method="POST" action="{{ route('leave-requests.reject', $leaveRequest) }}">@csrf<button class="text-xs text-rose-600" type="submit">Reject</button></form>@endif @endcan @can('cancel', $leaveRequest) @if(in_array($leaveRequest->status, ['pending', 'approved'], true))<form method="POST" action="{{ route('leave-requests.cancel', $leaveRequest) }}">@csrf<button class="text-xs text-slate-600" type="submit">Cancel</button></form>@endif @endcan @can('delete', $leaveRequest) @if($leaveRequest->isPending())<form method="POST" action="{{ route('leave-requests.destroy', $leaveRequest) }}">@csrf @method('DELETE')<button class="text-xs text-rose-600" type="submit">Delete</button></form>@endif @endcan</div></td></tr>@empty<tr><td colspan="6" class="py-6 text-slate-500">No leave requests found.</td></tr>@endforelse</tbody></table></div><div class="mt-4">{{ $requests->links() }}</div>
</div>
@endsection
