@csrf
<div class="mt-6 grid gap-5 md:grid-cols-2">
    @if(! isset($document) || ! $document)
        <div class="md:col-span-2"><label class="text-sm font-semibold" for="faculty_id">Employee</label><select class="input mt-1" id="faculty_id" name="faculty_id" required><option value="">Select employee</option>@foreach($employees as $employee)<option value="{{ $employee->id }}" @selected((int) old('faculty_id', $selectedEmployeeId ?? 0) === $employee->id)>{{ $employee->full_name }} ({{ $employee->employee_code }})</option>@endforeach</select><p class="mt-1 text-xs text-rose-600">@error('faculty_id'){{ $message }}@enderror</p></div>
    @else
        <div class="md:col-span-2 rounded-lg bg-slate-50 p-3 text-sm"><span class="font-semibold">Employee:</span> {{ $document->employee?->full_name }} ({{ $document->employee?->employee_code }})</div>
    @endif
    <div><label class="text-sm font-semibold" for="document_name">Document name</label><input class="input mt-1" id="document_name" name="document_name" value="{{ old('document_name', $document->document_name ?? '') }}" maxlength="255" required><p class="mt-1 text-xs text-rose-600">@error('document_name'){{ $message }}@enderror</p></div>
    <div><label class="text-sm font-semibold" for="document_type">Document type</label><input class="input mt-1" id="document_type" name="document_type" value="{{ old('document_type', $document->document_type ?? '') }}" maxlength="100" placeholder="e.g. Contract, ID proof, Certificate"><p class="mt-1 text-xs text-rose-600">@error('document_type'){{ $message }}@enderror</p></div>
    <div><label class="text-sm font-semibold" for="document_type_id">Existing document type (optional)</label><select class="input mt-1" id="document_type_id" name="document_type_id"><option value="">Do not link a master</option>@foreach($documentTypes as $type)<option value="{{ $type->id }}" @selected((int) old('document_type_id', $document->document_type_id ?? 0) === $type->id)>{{ $type->name }} ({{ $type->code }})</option>@endforeach</select><p class="mt-1 text-xs text-slate-500">The existing tenant document-type master can be reused; HR types may remain free text.</p><p class="mt-1 text-xs text-rose-600">@error('document_type_id'){{ $message }}@enderror</p></div>
    <div><label class="text-sm font-semibold" for="file">File {{ isset($document) && $document ? '(optional replacement)' : '' }}</label><input class="input mt-1" id="file" name="file" type="file" accept=".pdf,.jpg,.jpeg,.png,.doc,.docx" {{ isset($document) && $document ? '' : 'required' }}><p class="mt-1 text-xs text-slate-500">PDF, JPG, PNG, DOC or DOCX up to 10 MB. The stored path is generated privately.</p><p class="mt-1 text-xs text-rose-600">@error('file'){{ $message }}@enderror</p></div>
    <div><label class="text-sm font-semibold" for="issue_date">Issue date (optional)</label><input class="input mt-1" id="issue_date" name="issue_date" type="date" value="{{ old('issue_date', isset($document) && $document && $document->issue_date ? $document->issue_date->format('Y-m-d') : '') }}"><p class="mt-1 text-xs text-rose-600">@error('issue_date'){{ $message }}@enderror</p></div>
    <div><label class="text-sm font-semibold" for="expiry_date">Expiry date (optional)</label><input class="input mt-1" id="expiry_date" name="expiry_date" type="date" value="{{ old('expiry_date', isset($document) && $document && $document->expiry_date ? $document->expiry_date->format('Y-m-d') : '') }}"><p class="mt-1 text-xs text-rose-600">@error('expiry_date'){{ $message }}@enderror</p></div>
    <div class="md:col-span-2"><label class="text-sm font-semibold" for="remarks">Remarks (optional)</label><textarea class="input mt-1" id="remarks" name="remarks" rows="3" maxlength="2000">{{ old('remarks', $document->remarks ?? '') }}</textarea><p class="mt-1 text-xs text-rose-600">@error('remarks'){{ $message }}@enderror</p></div>
    <div class="md:col-span-2 flex gap-2"><button class="button" type="submit">{{ $submitLabel }}</button><a class="button !bg-slate-200 !text-slate-700" href="{{ route('employee-documents.index') }}">Cancel</a></div>
</div>
