@extends('layouts.app')
@section('title', 'Employee Documents')
@section('content')
<div class="panel">
    <div class="flex flex-wrap items-start justify-between gap-4"><div><h2 class="panel-title">Employee Documents</h2><p class="panel-subtitle">Private documents linked to Staff / Employee records. Downloads are authorized and streamed by the server.</p></div>@can('create', App\Models\EmployeeDocument::class)<a class="button" href="{{ route('employee-documents.create') }}">+ Upload document</a>@endcan</div>
    <form method="GET" action="{{ route('employee-documents.index') }}" class="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><input class="input" type="search" name="search" value="{{ $search }}" placeholder="Search document, file, employee"><select class="input" name="employee_id"><option value="">All employees</option>@foreach($employees as $employee)<option value="{{ $employee->id }}" @selected((int) $employee_id === $employee->id)>{{ $employee->full_name }} ({{ $employee->employee_code }})</option>@endforeach</select><input class="input" name="document_type" value="{{ $document_type }}" placeholder="Document type"><div class="flex gap-2"><button class="button" type="submit">Filter</button>@if($search !== '' || $employee_id || $document_type)<a class="button !bg-slate-200 !text-slate-700" href="{{ route('employee-documents.index') }}">Clear</a>@endif</div></form>
    <div class="mt-8 overflow-x-auto"><table class="w-full text-left text-sm"><thead><tr class="border-b text-slate-500"><th class="py-3">Document</th><th>Employee</th><th>Type</th><th>Issue / Expiry</th><th>File</th><th class="text-right">Actions</th></tr></thead><tbody>
        @forelse($documents as $document)
            <tr class="border-b"><td class="py-3"><a class="font-medium text-indigo-600 hover:underline" href="{{ route('employee-documents.show', $document) }}">{{ $document->document_name }}</a>@if($document->remarks)<p class="mt-0.5 max-w-xs truncate text-xs text-slate-500">{{ $document->remarks }}</p>@endif</td><td>{{ $document->employee?->full_name ?? '—' }}<div class="text-xs text-slate-500">{{ $document->employee?->employee_code }}</div></td><td>{{ $document->document_type ?: $document->documentTypeMaster?->name ?: '—' }}</td><td>{{ $document->issue_date?->format('M j, Y') ?? '—' }}<br><span class="text-xs {{ $document->isExpired() ? 'text-rose-600' : 'text-slate-500' }}">{{ $document->expiry_date ? 'expires '.$document->expiry_date->format('M j, Y') : 'No expiry' }}</span></td><td class="text-xs text-slate-500">{{ $document->original_filename }}<br>{{ $document->sizeInKb() }} KB</td><td class="text-right"><div class="flex flex-wrap justify-end gap-2">@can('download', $document)<a class="text-xs font-semibold text-indigo-600 hover:underline" href="{{ route('employee-documents.download', $document) }}">Download</a>@endcan @can('update', $document)<a class="text-xs font-semibold text-slate-600 hover:underline" href="{{ route('employee-documents.edit', $document) }}">Edit</a>@endcan @can('delete', $document)<form method="POST" action="{{ route('employee-documents.destroy', $document) }}" onsubmit="return confirm(@js('Delete this employee document?'))">@csrf @method('DELETE')<button class="text-xs font-semibold text-rose-600 hover:underline" type="submit">Delete</button></form>@endcan</div></td></tr>
        @empty <tr><td class="py-6 text-slate-500" colspan="6">No employee documents found.</td></tr>@endforelse
    </tbody></table></div><div class="mt-4 flex flex-wrap items-center justify-between gap-2"><p class="text-xs text-slate-500">Showing {{ $documents->firstItem() ?? 0 }}–{{ $documents->lastItem() ?? 0 }} of {{ $documents->total() }} documents.</p>{{ $documents->links() }}</div>
</div>
@endsection
