@extends('layouts.app')
@section('title', 'Fines / Penalties')
@section('content')
<div class="panel" data-bulk-scope>
 <div class="flex flex-wrap items-start justify-between gap-4"><div><h2 class="panel-title">Fines / Penalties</h2><p class="panel-subtitle">Overdue fines assessed from the active college's circulation history.</p></div></div>
 @can('create', App\Models\LibraryFine::class)<div class="mt-6 rounded-lg border border-slate-200 bg-slate-50 p-4"><h3 class="font-semibold text-slate-800">Eligible overdue transactions</h3><div class="mt-3 overflow-x-auto"><table class="w-full text-left text-sm"><thead><tr class="border-b text-slate-500"><th class="py-2">Book</th><th>Member</th><th>Due</th><th class="text-right">Action</th></tr></thead><tbody>@forelse($transactions as $transaction)<tr class="border-b"><td class="py-2 font-medium">{{ $transaction->bookCopy->book->title ?? '—' }}</td><td>{{ $transaction->libraryMember->member_code ?? '—' }}</td><td>{{ $transaction->due_on?->format('d M Y') }}</td><td><form method="POST" action="{{ route('library-fines.store') }}" class="flex justify-end gap-2">@csrf<input type="hidden" name="library_transaction_id" value="{{ $transaction->id }}"><input name="rate_per_day" type="number" step="0.01" min="0.01" required placeholder="Rate/day" class="input w-28"><button class="button" type="submit">Assess fine</button></form></td></tr>@empty<tr><td colspan="4" class="py-4 text-slate-500">No overdue transactions are currently eligible.</td></tr>@endforelse</tbody></table></div></div>@endcan
 {{-- Bulk selection over the paginated fines list (the "eligible overdue transactions" worklist above stays a single-record assess/pay workflow). Export only — the shared handler re-queries every ticked id inside the active college and re-authorizes each record before the CSV endpoint streams. --}}
 <x-list.bulk-selection-bar module="library_fines">
  @if(auth()->user()?->hasPermission('library_fines.view'))<button type="button" data-bulk-action="export" class="button !py-2 !text-xs font-semibold">Export selected</button>@endif
 </x-list.bulk-selection-bar>
 <div class="mt-6 overflow-x-auto"><table class="w-full text-left text-sm"><thead><tr class="border-b text-slate-500"><th class="w-10 py-2"><x-list.select-all /></th><th class="py-2">Member</th><th>Book</th><th>Period</th><th>Assessed</th><th>Outstanding</th><th>Status</th><th class="text-right">Actions</th></tr></thead><tbody>@forelse($fines as $fine)<tr class="border-b"><td class="py-2"><x-list.row-checkbox :id="$fine->id" /></td><td class="py-2">{{ $fine->member->member_code ?? '—' }}</td><td>{{ $fine->transaction->bookCopy->book->title ?? '—' }}</td><td>{{ $fine->period_start?->format('d M Y') }} – {{ $fine->period_end?->format('d M Y') }}</td><td>{{ number_format((float) $fine->assessed_amount, 2) }}</td><td>{{ number_format((float) $fine->outstanding(), 2) }}</td><td><span class="rounded-full px-3 py-1 text-xs font-semibold {{ $fine->status === 'paid' ? 'bg-emerald-100 text-emerald-700' : 'bg-amber-100 text-amber-700' }}">{{ ucfirst($fine->status) }}</span></td><td class="py-2"><div class="flex justify-end">@can('pay', $fine) @if($fine->status !== 'paid')<form method="POST" action="{{ route('library-fines.pay', $fine) }}" class="flex gap-2">@csrf<input name="payment_reference" placeholder="Reference" class="input w-28"><button class="button !bg-slate-200 !text-slate-700" type="submit">Record payment</button></form>@endif @endcan</div></td></tr>@empty<tr><td colspan="8" class="py-4 text-slate-500">No fines assessed yet for this college.</td></tr>@endforelse</tbody></table></div>
 <div class="mt-6">{{ $fines->links() }}</div>
</div>
@endsection