<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up(): void {
  Schema::create('academic_subject_enrollments', function(Blueprint $t){$t->id();$t->foreignId('college_id')->constrained()->cascadeOnDelete();$t->foreignId('student_id')->constrained()->cascadeOnDelete();$t->foreignId('student_enrollment_id')->constrained('student_enrollments')->cascadeOnDelete();$t->foreignId('academic_year_id')->constrained()->cascadeOnDelete();$t->foreignId('academic_term_id')->constrained()->cascadeOnDelete();$t->foreignId('program_id')->constrained()->cascadeOnDelete();$t->foreignId('section_id')->constrained()->cascadeOnDelete();$t->foreignId('subject_id')->constrained()->cascadeOnDelete();$t->string('status',20)->default('active');$t->date('enrollment_date');$t->text('remarks')->nullable();$t->timestamps();$t->softDeletes();$t->unique(['college_id','student_enrollment_id','subject_id','academic_term_id','status'],'ase_active_unique');$t->index(['college_id','student_id','academic_term_id']);});
  Schema::create('academic_timetables', function(Blueprint $t){$t->id();$t->foreignId('college_id')->constrained()->cascadeOnDelete();$t->foreignId('academic_year_id')->constrained()->cascadeOnDelete();$t->foreignId('academic_term_id')->constrained()->cascadeOnDelete();$t->foreignId('program_id')->constrained()->cascadeOnDelete();$t->foreignId('section_id')->constrained()->cascadeOnDelete();$t->foreignId('subject_id')->constrained()->cascadeOnDelete();$t->foreignId('faculty_id')->constrained()->cascadeOnDelete();$t->foreignId('campus_id')->nullable()->constrained()->nullOnDelete();$t->string('room')->nullable();$t->unsignedTinyInteger('day_of_week');$t->unsignedSmallInteger('period')->nullable();$t->time('start_time');$t->time('end_time');$t->string('status',20)->default('active');$t->text('remarks')->nullable();$t->timestamps();$t->softDeletes();$t->index(['college_id','section_id','day_of_week']);$t->index(['college_id','faculty_id','day_of_week']);$t->index(['college_id','room','day_of_week']);});
  Schema::create('academic_attendances', function(Blueprint $t){$t->id();$t->foreignId('college_id')->constrained()->cascadeOnDelete();$t->foreignId('student_id')->constrained()->cascadeOnDelete();$t->foreignId('student_enrollment_id')->constrained('student_enrollments')->cascadeOnDelete();$t->foreignId('student_subject_enrollment_id')->constrained('academic_subject_enrollments')->cascadeOnDelete();$t->foreignId('academic_year_id')->constrained()->cascadeOnDelete();$t->foreignId('academic_term_id')->constrained()->cascadeOnDelete();$t->foreignId('section_id')->constrained()->cascadeOnDelete();$t->foreignId('subject_id')->constrained()->cascadeOnDelete();$t->foreignId('faculty_id')->constrained()->cascadeOnDelete();$t->date('attendance_date');$t->string('status',20);$t->text('remarks')->nullable();$t->timestamps();$t->unique(['college_id','student_id','subject_id','attendance_date','academic_term_id'],'attendance_unique');$t->index(['college_id','section_id','attendance_date']);});
  Schema::create('academic_calendar_events', function(Blueprint $t){$t->id();$t->foreignId('college_id')->constrained()->cascadeOnDelete();$t->foreignId('academic_year_id')->constrained()->cascadeOnDelete();$t->foreignId('academic_term_id')->nullable()->constrained()->nullOnDelete();$t->string('title');$t->string('event_type',50);$t->date('start_date');$t->date('end_date');$t->text('description')->nullable();$t->string('status',20)->default('published');$t->timestamps();$t->softDeletes();$t->index(['college_id','academic_year_id','start_date']);});
 }
 public function down(): void { Schema::dropIfExists('academic_calendar_events');Schema::dropIfExists('academic_attendances');Schema::dropIfExists('academic_timetables');Schema::dropIfExists('academic_subject_enrollments'); }
};
