@extends('layouts.app')
@section('title', 'HR Reports')
@section('content')
<div class="panel">
    <div><h2 class="panel-title">HR Reports</h2><p class="panel-subtitle">Live read-only summaries from attendance, leave, and payroll records.</p></div>
    <div class="mt-6 flex flex-wrap gap-2"><a class="button {{ $report === 'attendance' ? '' : '!bg-slate-200 !text-slate-700' }}" href="{{ route('hr-reports.index', ['report' => 'attendance']) }}">Attendance</a><a class="button {{ $report === 'leave' ? '' : '!bg-slate-200 !text-slate-700' }}" href="{{ route('hr-reports.index', ['report' => 'leave']) }}">Leave</a><a class="button {{ $report === 'payroll' ? '' : '!bg-slate-200 !text-slate-700' }}" href="{{ route('hr-reports.index', ['report' => 'payroll']) }}">Payroll</a></div>
    <form method="GET" class="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><input type="hidden" name="report" value="{{ $report }}"><select class="input" name="faculty_id"><option value="">All employees</option>@foreach($employees as $employee)<option value="{{ $employee->id }}" @selected((int)($filters['faculty_id'] ?? 0) === $employee->id)>{{ $employee->full_name }}</option>@endforeach</select>@if($report !== 'payroll')<input class="input" type="date" name="from" value="{{ $filters['from'] ?? '' }}"><input class="input" type="date" name="to" value="{{ $filters['to'] ?? '' }}"><select class="input" name="status"><option value="">All statuses</option>@foreach(($report === 'attendance' ? $attendanceStatuses : $leaveStatuses) as $status)<option value="{{ $status }}" @selected(($filters['status'] ?? '') === $status)>{{ ucfirst($status) }}</option>@endforeach</select>@else<input class="input" type="month" name="from" value="{{ $filters['from'] ?? '' }}"><input class="input" type="month" name="to" value="{{ $filters['to'] ?? '' }}">@endif<button class="button" type="submit">Run report</button></form>
    <div class="mt-8 overflow-x-auto">@if($report === 'attendance')<table class="w-full text-left text-sm"><thead><tr class="border-b text-slate-500"><th class="py-3">Employee</th><th>Status</th><th>Total days</th></tr></thead><tbody>@forelse($rows as $row)<tr class="border-b"><td class="py-3">{{ $row['employee']?->full_name }}</td><td>{{ ucfirst($row['status']) }}</td><td>{{ $row['total'] }}</td></tr>@empty<tr><td colspan="3" class="py-6 text-slate-500">No attendance data for these filters.</td></tr>@endforelse</tbody></table>@elseif($report === 'leave')<table class="w-full text-left text-sm"><thead><tr class="border-b text-slate-500"><th class="py-3">Employee</th><th>Status</th><th>Requests</th><th>Total days</th></tr></thead><tbody>@forelse($rows as $row)<tr class="border-b"><td class="py-3">{{ $row['employee']?->full_name }}</td><td>{{ ucfirst($row['status']) }}</td><td>{{ $row['requests'] }}</td><td>{{ $row['total_days'] }}</td></tr>@empty<tr><td colspan="4" class="py-6 text-slate-500">No leave data for these filters.</td></tr>@endforelse</tbody></table>@else<table class="w-full text-left text-sm"><thead><tr class="border-b text-slate-500"><th class="py-3">Employee</th><th>Payrolls</th><th>Gross</th><th>Deductions</th><th>Net</th></tr></thead><tbody>@forelse($rows as $row)<tr class="border-b"><td class="py-3">{{ $row['employee']?->full_name }}</td><td>{{ $row['payrolls'] }}</td><td>{{ number_format($row['gross_amount'], 2) }}</td><td>{{ number_format($row['total_deductions'], 2) }}</td><td>{{ number_format($row['net_amount'], 2) }}</td></tr>@empty<tr><td colspan="5" class="py-6 text-slate-500">No payroll data for these filters.</td></tr>@endforelse</tbody></table>@endif</div>
</div>
@endsection
