<?php

namespace App\Http\Requests\StudentDocument;

use App\Models\StudentDocument;
use App\Support\Tenancy\TenantContext;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class StoreStudentDocumentRequest extends FormRequest
{
    public function authorize(): bool
    {
        return $this->user()?->can('create', StudentDocument::class) ?? false;
    }

    /**
     * college_id, file_path, verification state and the uploader are never
     * taken from the browser: the tenant is the server-side context, the stored
     * path is generated by StudentDocumentService, and verification starts as
     * "pending".
     *
     * File rules are the first line of defence (type + hard 5 MB ceiling); the
     * per-college document-type configuration (extensions / max size) and the
     * executable-extension blacklist are enforced again in the service, because
     * server-side validation is authoritative.
     */
    public function rules(): array
    {
        $collegeId = app(TenantContext::class)->id();

        return [
            'student_id' => ['required', 'integer', Rule::exists('students', 'id')->where('college_id', $collegeId)->whereNull('deleted_at')],
            'document_type_id' => ['nullable', 'integer', Rule::exists('admission_document_types', 'id')->where('college_id', $collegeId)->whereNull('deleted_at')],
            'title' => ['required', 'string', 'max:255'],
            'file' => ['required', 'file', 'max:5120', 'mimes:pdf,jpg,jpeg,png'],
            'issue_date' => ['nullable', 'date'],
            'expiry_date' => ['nullable', 'date', 'after_or_equal:issue_date'],
            'remarks' => ['nullable', 'string', 'max:2000'],
        ];
    }

    protected function prepareForValidation(): void
    {
        $this->request->remove('college_id');
        $this->request->remove('file_path');
        $this->request->remove('original_filename');
        $this->request->remove('mime_type');
        $this->request->remove('file_size');
        $this->request->remove('verification_status');
        $this->request->remove('verified_by');
        $this->request->remove('verified_at');
        $this->request->remove('uploaded_by');
        $this->request->remove('created_by');
        $this->request->remove('updated_by');
    }
}
