<?php

namespace App\Http\Requests\Transport;

use App\Models\VehicleDocument;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

/**
 * Vehicle document upload — only validated fields leave this boundary.
 *
 * college_id, file_path, file metadata and actor fields are NEVER input: the
 * tenant is the server-side context, the stored path is generated by
 * VehicleDocumentService, and the uploader is the authenticated user.
 *
 * File rules are the first line of defence (type + hard 5 MB ceiling); the
 * executable-extension blacklist and MIME checks are enforced again in the
 * service, because server-side validation is authoritative.
 */
class StoreVehicleDocumentRequest extends FormRequest
{
    public function authorize(): bool
    {
        return $this->user()?->can('create', VehicleDocument::class) ?? false;
    }

    protected function prepareForValidation(): void
    {
        foreach (['college_id', 'file_path', 'original_filename', 'mime_type', 'file_size', 'uploaded_by', 'created_by', 'updated_by'] as $field) {
            $this->request->remove($field);
        }
    }

    public function rules(): array
    {
        $collegeId = app(\App\Support\Tenancy\TenantContext::class)->id();

        return [
            'vehicle_id' => ['required', 'integer', Rule::exists('vehicles', 'id')->where('college_id', $collegeId)->whereNull('deleted_at')],
            // Extensible label (not a closed enum): a college may use any
            // document category; the conventional set is only a suggestion.
            'document_type' => ['required', 'string', 'max:100'],
            'document_number' => ['nullable', 'string', 'max:100'],
            'issue_date' => ['nullable', 'date_format:Y-m-d'],
            'expiry_date' => ['nullable', 'date_format:Y-m-d', 'after_or_equal:issue_date'],
            'file' => ['required', 'file', 'max:5120', 'mimes:pdf,jpg,jpeg,png'],
            'remarks' => ['nullable', 'string', 'max:2000'],
        ];
    }

    public function messages(): array
    {
        return [
            'expiry_date.after_or_equal' => 'The expiry date must not be before the issue date.',
        ];
    }
}
