<?php
namespace App\Http\Controllers;
use App\Models\{AcademicAttendance,AcademicCalendarEvent,AcademicSubjectEnrollment,AcademicTimetable,AcademicYear,AcademicTerm,Campus,Faculty,Program,Section,Student,StudentEnrollment,Subject};
use App\Support\Tenancy\TenantContext; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB; use Illuminate\Validation\Rule;
class AcademicsController extends Controller {
 private function college():int{return (int)app(TenantContext::class)->require()->id;}
 private function authorizePermission(string $p):void{abort_unless(auth()->user()?->hasPermission($p,$this->college()),403);}
 private function scoped(string $model,int $id){return $model::query()->where('id',$id)->where('college_id',$this->college())->firstOrFail();}
 private function refRules(string $table):array{return ['required','integer',Rule::exists($table,'id')->where(fn($q)=>$q->where('college_id',$this->college()))];}
 public function subjectEnrollments(Request $r){$this->authorizePermission('academic_subject_enrollments.view');$q=AcademicSubjectEnrollment::with(['student','subject','academicTerm','section'])->latest();if($r->filled('search'))$q->whereHas('student',fn($x)=>$x->where('first_name','like','%'.$r->search.'%')->orWhere('last_name','like','%'.$r->search.'%'))->orWhereHas('subject',fn($x)=>$x->where('name','like','%'.$r->search.'%'));return view('academics.subject-enrollments.index',['items'=>$q->paginate(20)->withQueryString()]);}
 public function createSubjectEnrollment(){ $this->authorizePermission('academic_subject_enrollments.create'); return view('academics.subject-enrollments.form',$this->lists()); }
 private function lists():array{return ['students'=>Student::orderBy('first_name')->get(),'enrollments'=>StudentEnrollment::with('student')->whereIn('status',['active','completed'])->get(),'years'=>AcademicYear::orderByDesc('id')->get(),'terms'=>AcademicTerm::orderBy('sequence')->get(),'programs'=>Program::orderBy('name')->get(),'sections'=>Section::orderBy('name')->get(),'subjects'=>Subject::orderBy('name')->get(),'faculties'=>Faculty::orderBy('first_name')->get(),'campuses'=>Campus::orderBy('name')->get()];}
 public function storeSubjectEnrollment(Request $r){$this->authorizePermission('academic_subject_enrollments.create');$c=$this->college();$v=$r->validate(['student_id'=>$this->refRules('students'),'student_enrollment_id'=>$this->refRules('student_enrollments'),'academic_year_id'=>$this->refRules('academic_years'),'academic_term_id'=>$this->refRules('academic_terms'),'program_id'=>$this->refRules('programs'),'section_id'=>$this->refRules('sections'),'subject_id'=>$this->refRules('subjects'),'status'=>['required',Rule::in(['active','dropped','completed'])],'enrollment_date'=>'required|date','remarks'=>'nullable|string']);$en=StudentEnrollment::where('id',$v['student_enrollment_id'])->where('college_id',$c)->firstOrFail();$term=AcademicTerm::whereKey($v['academic_term_id'])->where('college_id',$c)->firstOrFail();$section=Section::whereKey($v['section_id'])->where('college_id',$c)->firstOrFail();abort_unless($en->student_id==$v['student_id']&&$en->academic_year_id==$v['academic_year_id']&&$en->program_id==$v['program_id']&&$en->section_id==$v['section_id']&&$term->academic_year_id==$v['academic_year_id']&&$section->academic_year_id==$v['academic_year_id']&&$section->program_id==$v['program_id'],422,'Enrollment context does not match.');DB::transaction(fn()=>AcademicSubjectEnrollment::create($v+['college_id'=>$c]));return redirect()->route('academic-subject-enrollments.index')->with('success','Subject enrollment created.');}
 public function updateSubjectEnrollment(Request $r,AcademicSubjectEnrollment $item){$this->authorizePermission('academic_subject_enrollments.update');$v=$r->validate(['status'=>['required',Rule::in(['active','dropped','completed'])],'enrollment_date'=>'required|date','remarks'=>'nullable|string']);$item->update($v);return back()->with('success','Subject enrollment updated.');}
 public function destroySubjectEnrollment(AcademicSubjectEnrollment $item){$this->authorizePermission('academic_subject_enrollments.delete');$item->delete();return back()->with('success','Subject enrollment removed.');}
 public function sections(Request $r){$this->authorizePermission('academic_sections.view');$items=Section::with(['academicYear','program','campus'])->withCount('assignments')->withCount(['assignments as subject_count'=>fn($q)=>$q->select(DB::raw('count(distinct subject_id)'))])->paginate(20);return view('academics.sections.index',compact('items'));}
 public function section(Section $section){$this->authorizePermission('academic_sections.view');$section->load(['academicYear','program','campus','assignments.subject','assignments.faculty']);$section->loadCount(['assignments','assignments as subject_count'=>fn($q)=>$q->select(DB::raw('count(distinct subject_id)'))]);$section->student_count=StudentEnrollment::where('section_id',$section->id)->where('status','active')->count();$section->timetable_count=AcademicTimetable::where('section_id',$section->id)->where('status','active')->count();return view('academics.sections.show',compact('section'));}
 public function timetables(Request $r){$this->authorizePermission('academic_timetables.view');$items=AcademicTimetable::with(['section','subject','faculty'])->orderBy('day_of_week')->orderBy('start_time')->paginate(30);return view('academics.timetables.index',compact('items'));}
 public function createTimetable(){ $this->authorizePermission('academic_timetables.create');return view('academics.timetables.form',$this->lists()); }
 public function storeTimetable(Request $r){$this->authorizePermission('academic_timetables.create');$c=$this->college();$v=$r->validate(['academic_year_id'=>$this->refRules('academic_years'),'academic_term_id'=>$this->refRules('academic_terms'),'program_id'=>$this->refRules('programs'),'section_id'=>$this->refRules('sections'),'subject_id'=>$this->refRules('subjects'),'faculty_id'=>$this->refRules('faculties'),'campus_id'=>['nullable',...$this->refRules('campuses')],'room'=>'nullable|string|max:100','day_of_week'=>'required|integer|between:1,7','period'=>'nullable|integer|min:1','start_time'=>'required|date_format:H:i','end_time'=>'required|date_format:H:i|after:start_time','status'=>'required|in:active,inactive','remarks'=>'nullable|string']);$section=Section::whereKey($v['section_id'])->where('college_id',$c)->firstOrFail();$term=AcademicTerm::whereKey($v['academic_term_id'])->where('college_id',$c)->firstOrFail();abort_unless($section->academic_year_id==$v['academic_year_id']&&$section->program_id==$v['program_id']&&$term->academic_year_id==$v['academic_year_id'],422,'Timetable context does not match.');$this->ensureNoConflict($v);AcademicTimetable::create($v+['college_id'=>$c]);return redirect()->route('academic-timetables.index')->with('success','Timetable entry created.');}
 private function ensureNoConflict(array $v,?int $except=null):void{$q=AcademicTimetable::where('college_id',$this->college())->where('academic_term_id',$v['academic_term_id'])->where('day_of_week',$v['day_of_week'])->where('status','active')->when($except,fn($x)=>$x->where('id','!=',$except))->where(function($x)use($v){$x->where('start_time','<',$v['end_time'])->where('end_time','>',$v['start_time']);});$conflict=$q->where(fn($x)=>$x->where('faculty_id',$v['faculty_id'])->orWhere('section_id',$v['section_id'])->when(filled($v['room']??null),fn($r)=>$r->orWhere('room',$v['room'])))->exists();if($conflict)abort(422,'Timetable conflict: faculty, section, or room is already occupied in this time slot.');}
 public function updateTimetable(Request $r,AcademicTimetable $item){$this->authorizePermission('academic_timetables.update');$v=$r->validate(['day_of_week'=>'required|integer|between:1,7','period'=>'nullable|integer|min:1','start_time'=>'required|date_format:H:i','end_time'=>'required|date_format:H:i|after:start_time','room'=>'nullable|string|max:100','status'=>'required|in:active,inactive','remarks'=>'nullable|string']);$this->ensureNoConflict(array_merge($item->toArray(),$v),$item->id);$item->update($v);return back()->with('success','Timetable updated.');}
 public function destroyTimetable(AcademicTimetable $item){$this->authorizePermission('academic_timetables.delete');$item->delete();return back()->with('success','Timetable entry removed.');}
 public function attendance(Request $r){$this->authorizePermission('academic_attendance.view');$items=AcademicAttendance::with(['student','subject','section'])->latest('attendance_date')->paginate(30);return view('academics.attendance.index',compact('items'));}
 public function bulkAttendance(Request $r){$this->authorizePermission('academic_attendance.create');$data=$r->validate(['records'=>'required|array|min:1','records.*.student_subject_enrollment_id'=>$this->refRules('academic_subject_enrollments'),'records.*.attendance_date'=>'required|date','records.*.status'=>'required|in:present,absent,late,leave','records.*.faculty_id'=>$this->refRules('faculties'),'records.*.remarks'=>'nullable|string']);DB::transaction(function()use($data){foreach($data['records'] as $record){$this->saveAttendance($record);}});return back()->with('success','Bulk attendance saved.');}
 private function saveAttendance(array $input):void{$c=$this->college();$s=AcademicSubjectEnrollment::whereKey($input['student_subject_enrollment_id'])->where('college_id',$c)->firstOrFail();$v=['college_id'=>$c,'student_id'=>$s->student_id,'student_enrollment_id'=>$s->student_enrollment_id,'student_subject_enrollment_id'=>$s->id,'academic_year_id'=>$s->academic_year_id,'academic_term_id'=>$s->academic_term_id,'section_id'=>$s->section_id,'subject_id'=>$s->subject_id,'faculty_id'=>$input['faculty_id'],'attendance_date'=>$input['attendance_date'],'status'=>$input['status'],'remarks'=>$input['remarks']??null];AcademicAttendance::updateOrCreate(['college_id'=>$c,'student_id'=>$v['student_id'],'subject_id'=>$v['subject_id'],'attendance_date'=>$v['attendance_date'],'academic_term_id'=>$v['academic_term_id']],$v);}
 public function storeAttendance(Request $r){$this->authorizePermission('academic_attendance.create');$c=$this->college();$v=$r->validate(['student_subject_enrollment_id'=>$this->refRules('academic_subject_enrollments'),'attendance_date'=>'required|date','status'=>'required|in:present,absent,late,leave','remarks'=>'nullable|string']);$s=AcademicSubjectEnrollment::whereKey($v['student_subject_enrollment_id'])->where('college_id',$c)->firstOrFail();$v+=['college_id'=>$c,'student_id'=>$s->student_id,'student_enrollment_id'=>$s->student_enrollment_id,'academic_year_id'=>$s->academic_year_id,'academic_term_id'=>$s->academic_term_id,'section_id'=>$s->section_id,'subject_id'=>$s->subject_id,'faculty_id'=>$r->validate(['faculty_id'=>$this->refRules('faculties')])['faculty_id']];AcademicAttendance::updateOrCreate(['college_id'=>$c,'student_id'=>$v['student_id'],'subject_id'=>$v['subject_id'],'attendance_date'=>$v['attendance_date'],'academic_term_id'=>$v['academic_term_id']],$v);return back()->with('success','Attendance saved.');}
 public function updateCalendar(Request $r,AcademicCalendarEvent $item){$this->authorizePermission('academic_calendar.update');$v=$r->validate(['title'=>'required|string|max:255','event_type'=>'required|string|max:50','start_date'=>'required|date','end_date'=>'required|date|after_or_equal:start_date','academic_term_id'=>['nullable',...$this->refRules('academic_terms')],'description'=>'nullable|string','status'=>'required|in:draft,published,cancelled']);$item->update($v);return back()->with('success','Calendar event updated.');}
 public function destroyCalendar(AcademicCalendarEvent $item){$this->authorizePermission('academic_calendar.delete');$item->delete();return back()->with('success','Calendar event removed.');}
 public function calendar(Request $r){$this->authorizePermission('academic_calendar.view');$items=AcademicCalendarEvent::with(['academicYear','academicTerm'])->orderBy('start_date')->paginate(30);return view('academics.calendar.index',compact('items'));}
 public function createCalendar(){ $this->authorizePermission('academic_calendar.create');return view('academics.calendar.form',$this->lists()); }
 public function storeCalendar(Request $r){$this->authorizePermission('academic_calendar.create');$v=$r->validate(['title'=>'required|string|max:255','event_type'=>'required|string|max:50','start_date'=>'required|date','end_date'=>'required|date|after_or_equal:start_date','academic_year_id'=>$this->refRules('academic_years'),'academic_term_id'=>['nullable',...$this->refRules('academic_terms')],'description'=>'nullable|string','status'=>'required|in:draft,published,cancelled']);AcademicCalendarEvent::create($v+['college_id'=>$this->college()]);return redirect()->route('academic-calendar.index')->with('success','Calendar event created.');}
 public function workload(){ $this->authorizePermission('academic_workload.view');$items=AcademicTimetable::query()->select('faculty_id','subject_id','section_id','academic_year_id','academic_term_id',DB::raw('count(*) as periods'),DB::raw('sum(TIMESTAMPDIFF(MINUTE,start_time,end_time))/60 as weekly_hours'))->where('status','active')->with(['faculty','subject','section','academicYear','academicTerm'])->groupBy('faculty_id','subject_id','section_id','academic_year_id','academic_term_id')->paginate(30);return view('academics.workload.index',compact('items'));}
}
