<?php

namespace App\Models;

use App\Domain\Foundation\Traits\BelongsToCollege;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Private, tenant-scoped document belonging to a Faculty/Staff employee.
 *
 * `file_path` is server-generated by EmployeeDocumentService and is never
 * rendered or accepted as a browser-controlled download URL.
 */
class EmployeeDocument extends Model
{
    use HasFactory, SoftDeletes, BelongsToCollege;

    protected $fillable = [
        'college_id',
        'faculty_id',
        // employee_id is an input/model alias for faculty_id; see the mutator.
        'employee_id',
        'document_name',
        'document_type',
        'document_type_id',
        'file_path',
        'original_filename',
        'mime_type',
        'file_size',
        'issue_date',
        'expiry_date',
        'remarks',
        'uploaded_by',
        'created_by',
        'updated_by',
    ];

    protected function casts(): array
    {
        return [
            'file_size' => 'integer',
            'issue_date' => 'date',
            'expiry_date' => 'date',
        ];
    }

    public function employee(): BelongsTo
    {
        return $this->belongsTo(Employee::class, 'faculty_id');
    }

    public function staff(): BelongsTo
    {
        return $this->belongsTo(Faculty::class, 'faculty_id');
    }

    public function faculty(): BelongsTo
    {
        return $this->belongsTo(Faculty::class, 'faculty_id');
    }

    public function documentTypeMaster(): BelongsTo
    {
        return $this->belongsTo(AdmissionDocumentType::class, 'document_type_id');
    }

    public function uploadedBy(): BelongsTo
    {
        return $this->belongsTo(User::class, 'uploaded_by');
    }

    public function creator(): BelongsTo
    {
        return $this->belongsTo(User::class, 'created_by');
    }

    public function updater(): BelongsTo
    {
        return $this->belongsTo(User::class, 'updated_by');
    }

    public function isExpired(): bool
    {
        return $this->expiry_date !== null && $this->expiry_date->isPast();
    }

    public function sizeInKb(): float
    {
        return round(((int) $this->file_size) / 1024, 1);
    }

    /**
     * Accept employee terminology without persisting a duplicate foreign key.
     */
    public function setEmployeeIdAttribute($value): void
    {
        $this->attributes['faculty_id'] = $value;
    }

    public function getEmployeeIdAttribute(): mixed
    {
        return $this->attributes['faculty_id'] ?? null;
    }

    public function getTitleAttribute(): ?string
    {
        return $this->attributes['document_name'] ?? null;
    }

    public function setTitleAttribute($value): void
    {
        $this->attributes['document_name'] = $value;
    }
}
