@csrf <div class="mt-6 grid gap-5 md:grid-cols-2">
<div><label class="text-sm font-semibold" for="name">Name</label><input class="input mt-1" id="name" name="name" value="{{ old('name', $program->name ?? '') }}" required><p class="mt-1 text-xs text-rose-600">@error('name'){{ $message }}@enderror</p></div>
<div><label class="text-sm font-semibold" for="code">Code</label><input class="input mt-1" id="code" name="code" value="{{ old('code', $program->code ?? '') }}" maxlength="50" required><p class="mt-1 text-xs text-rose-600">@error('code'){{ $message }}@enderror</p></div>
<div><label class="text-sm font-semibold" for="short_name">Short name</label><input class="input mt-1" id="short_name" name="short_name" value="{{ old('short_name', $program->short_name ?? '') }}" maxlength="50"><p class="mt-1 text-xs text-rose-600">@error('short_name'){{ $message }}@enderror</p></div>
<div><label class="text-sm font-semibold" for="department_id">Department</label><select class="input mt-1" id="department_id" name="department_id"><option value="">College level (no department)</option>@foreach($departments as $department)<option value="{{ $department->id }}" @selected((int) old('department_id', $program->department_id ?? 0) === $department->id)>{{ $department->name }} ({{ $department->code }})</option>@endforeach</select><p class="mt-1 text-xs text-rose-600">@error('department_id'){{ $message }}@enderror</p></div>
<div><label class="text-sm font-semibold" for="status">Status</label><select class="input mt-1" id="status" name="status" required><option value="active" @selected(old('status', $program->status ?? 'active') === 'active')>Active</option><option value="inactive" @selected(old('status', $program->status ?? 'active') === 'inactive')>Inactive</option></select><p class="mt-1 text-xs text-rose-600">@error('status'){{ $message }}@enderror</p></div>
<div class="md:col-span-2"><label class="text-sm font-semibold" for="description">Description (optional)</label><textarea class="input mt-1" id="description" name="description" rows="3" maxlength="2000">{{ old('description', $program->description ?? '') }}</textarea><p class="mt-1 text-xs text-rose-600">@error('description'){{ $message }}@enderror</p></div>
<div class="md:col-span-2 flex gap-2"><button class="button" type="submit">{{ $submitLabel }}</button><a class="button !bg-slate-200 !text-slate-700" href="{{ route('programs.index') }}">Cancel</a></div>
</div>
