<?php
namespace App\Providers;
use App\Models\{AcademicSubjectEnrollment, AcademicTimetable, AcademicTerm, AcademicYear, Admission, AdmissionApplicant, AdmissionApplication, AdmissionDocument, AdmissionDocumentType, AdmissionEnquiry, AdmissionMeritEntry, AdmissionMeritList, Campus, College, Department, Examination, ExamAttendance, ExamMark, ExamSchedule, Faculty, FacultySubjectAssignment, InstitutionalSetting, Permission, Program, Role, Section, Student, StudentAcademicRecord, StudentDocument, StudentEnrollment, StudentPromotion, StudentTransfer, Subject};
use App\Policies\{AcademicSubjectEnrollmentPolicy, AcademicTimetablePolicy, AcademicTermPolicy, AcademicYearPolicy, AdmissionApplicantPolicy, AdmissionApplicationPolicy, AdmissionDocumentPolicy, AdmissionDocumentTypePolicy, AdmissionEnquiryPolicy, AdmissionMeritEntryPolicy, AdmissionMeritListPolicy, AdmissionPolicy, CampusPolicy, CollegePolicy, DepartmentPolicy, ExaminationPolicy, ExamAttendancePolicy, ExamMarkPolicy, ExamSchedulePolicy, FacultyPolicy, FacultySubjectAssignmentPolicy, InstitutionalSettingPolicy, PermissionPolicy, ProgramPolicy, RolePolicy, SectionPolicy, StudentAcademicRecordPolicy, StudentDocumentPolicy, StudentEnrollmentPolicy, StudentPolicy, StudentPromotionPolicy, StudentTransferPolicy, SubjectPolicy};
use Illuminate\Foundation\Support\Providers\AuthServiceProvider as ServiceProvider;
class AuthServiceProvider extends ServiceProvider
{
    protected $policies = [AcademicSubjectEnrollment::class => AcademicSubjectEnrollmentPolicy::class, AcademicTimetable::class => AcademicTimetablePolicy::class, College::class => CollegePolicy::class, Campus::class => CampusPolicy::class, Department::class => DepartmentPolicy::class, AcademicYear::class => AcademicYearPolicy::class, AcademicTerm::class => AcademicTermPolicy::class, Program::class => ProgramPolicy::class, Section::class => SectionPolicy::class, Subject::class => SubjectPolicy::class, Faculty::class => FacultyPolicy::class, FacultySubjectAssignment::class => FacultySubjectAssignmentPolicy::class, InstitutionalSetting::class => InstitutionalSettingPolicy::class, Role::class => RolePolicy::class, Permission::class => PermissionPolicy::class, AdmissionApplicant::class => AdmissionApplicantPolicy::class, AdmissionEnquiry::class => AdmissionEnquiryPolicy::class, AdmissionApplication::class => AdmissionApplicationPolicy::class, AdmissionDocumentType::class => AdmissionDocumentTypePolicy::class, AdmissionDocument::class => AdmissionDocumentPolicy::class, AdmissionMeritList::class => AdmissionMeritListPolicy::class, AdmissionMeritEntry::class => AdmissionMeritEntryPolicy::class, Admission::class => AdmissionPolicy::class, Student::class => StudentPolicy::class, StudentEnrollment::class => StudentEnrollmentPolicy::class, StudentAcademicRecord::class => StudentAcademicRecordPolicy::class, StudentDocument::class => StudentDocumentPolicy::class, StudentPromotion::class => StudentPromotionPolicy::class, StudentTransfer::class => StudentTransferPolicy::class, Examination::class => ExaminationPolicy::class, ExamSchedule::class => ExamSchedulePolicy::class, ExamAttendance::class => ExamAttendancePolicy::class, ExamMark::class => ExamMarkPolicy::class];
    public function boot(): void {}
}
