@extends('layouts.app')
@section('title', 'Notification Settings')
@section('content')
@include('administration.partials.context')
<div class="space-y-6">
    <div class="panel"><h2 class="panel-title">Notification Settings</h2><p class="panel-subtitle">Central access to configuration the existing Communication module actually supports. This screen never contacts an SMS or email provider.</p>
        <div class="mt-6 grid gap-4 md:grid-cols-2"><div class="rounded-xl bg-indigo-50 p-4"><h3 class="text-sm font-semibold text-indigo-800">Internal, in-app notifications</h3><p class="mt-2 text-sm text-indigo-700">Recipient addressing and delivery / read tracking remain in the existing notification workflow. There is no independent delivery toggle or provider configuration.</p>@can('viewAny', App\Models\CommunicationNotification::class)<a class="mt-3 inline-block text-sm font-semibold text-indigo-700 hover:underline" href="{{ route('notifications.index') }}">Open notifications →</a>@endcan</div><div class="rounded-xl bg-slate-50 p-4"><h3 class="text-sm font-semibold">SMS / email definitions only</h3><p class="mt-2 text-sm text-slate-600">Existing templates can be activated or deactivated for reuse. These are definitions, not external delivery services; activation does not send a message.</p></div></div>
        <h3 class="mt-6 text-sm font-semibold">Deployment-managed Communication limits (read-only)</h3><dl class="mt-3 grid gap-3 text-sm sm:grid-cols-3"><div class="rounded-xl bg-slate-50 p-3"><dt class="text-slate-500">Listing page size</dt><dd class="mt-1 font-semibold">{{ $limits['page_size'] }}</dd></div><div class="rounded-xl bg-slate-50 p-3"><dt class="text-slate-500">Recipient options per type</dt><dd class="mt-1 font-semibold">{{ $limits['recipient_options'] }}</dd></div><div class="rounded-xl bg-slate-50 p-3"><dt class="text-slate-500">Attachment ceiling</dt><dd class="mt-1 font-semibold">{{ $limits['attachment_kb'] }} KB</dd></div></dl>
    </div>
    @if($canTemplates)
        <div class="panel"><div class="flex flex-wrap justify-between gap-4"><div><h3 class="panel-title">College template availability</h3><p class="panel-subtitle">These are the same template rows used by Communication. Its template policies and audit service apply to every change.</p></div>@can('create', App\Models\CommunicationTemplate::class)<a class="button" href="{{ route('communication-templates.create') }}">+ New template</a>@endcan</div>
            <form method="GET" action="{{ route('admin.notification-settings.index') }}" class="mt-6 grid gap-3 md:grid-cols-3"><div><label class="label" for="channel">Template channel</label><select class="input" name="channel" id="channel"><option value="">All channels</option>@foreach($channels as $value => $label)<option value="{{ $value }}" @selected(($filters['channel'] ?? '') === $value)>{{ $label }}</option>@endforeach</select></div><div><label class="label" for="status">Availability</label><select class="input" name="status" id="status"><option value="">All statuses</option><option value="active" @selected(($filters['status'] ?? '') === 'active')>Active</option><option value="inactive" @selected(($filters['status'] ?? '') === 'inactive')>Inactive</option></select></div><div class="flex items-end gap-2"><button class="button" type="submit">Filter</button><a class="button !bg-slate-200 !text-slate-700" href="{{ route('admin.notification-settings.index') }}">Clear</a></div></form>
            <div class="mt-6 overflow-x-auto"><table class="w-full text-left text-sm"><thead><tr class="border-b text-slate-500"><th class="py-3 pr-4">Template</th><th class="pr-4">Channel</th><th class="pr-4">Availability</th><th class="text-right">Actions</th></tr></thead><tbody>@forelse($templates as $template)<tr class="border-b"><td class="py-3 pr-4"><a class="font-medium text-indigo-600 hover:underline" href="{{ route('communication-templates.show', $template) }}">{{ $template->name }}</a><p class="mt-1 font-mono text-xs text-slate-500">{{ $template->code }}</p></td><td class="pr-4">{{ $template->channelLabel() }}</td><td class="pr-4">@include('administration.partials.status', ['active' => $template->isActive()])</td><td class="text-right">@can('update', $template)<div class="flex flex-wrap justify-end gap-3"><a class="font-semibold text-indigo-600 hover:underline" href="{{ route('communication-templates.edit', $template) }}">Edit definition</a><form method="POST" action="{{ route('admin.notification-settings.templates.status', $template) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="{{ $template->isActive() ? 'inactive' : 'active' }}"><button class="font-semibold text-slate-600 hover:text-indigo-600" type="submit">{{ $template->isActive() ? 'Deactivate' : 'Activate' }}</button></form></div>@else<span class="text-xs text-slate-500">Read-only</span>@endcan</td></tr>@empty<tr><td class="py-6 text-slate-500" colspan="4">No existing college templates match the filters.</td></tr>@endforelse</tbody></table></div><div class="mt-4">{{ $templates->links() }}</div>
        </div>
    @else<div class="panel"><p class="text-sm text-slate-500">Your role can view notification configuration, but does not permit viewing or changing template definitions.</p></div>@endif
</div>
@endsection
